### ISSUE TITLE
Set up dev and production database connections

### ISSUE THREAD

**Issue by conor-jh** [team-skechers/Lunchin#6]
### User story
As a developer, I should be able to use a local database in development, and a remote database for production so that I can make changes without inadvertently introducing bugs to our production database

### Tasks
- [x] Set up database connection based on environment
- [x] Determine if manual action is needed by team members (if so, help everyone get setup)

**Comment by Donaldblanc** [comment]
Completed! Team will have to use the schema files to stage their local dev DB
